export const PRODUCTS = {
  guide: {
    id: 'guide',
    name: 'The Mindful Musicpreneur Guide',
    slug: 'mindful-musicpreneur-guide',
    price: 60,
    description: '200+ page career-shadow field guide for female musicians',
    image: '/360MindfulSystem.png',
    includes: [
      'The Mindful Musicpreneur Guide (200+ pages)',
      'Mindful Muse Quarterly Planner (complimentary bonus)',
      '450+ song Sonic Journey playlists',
      'The Woo of You section (MBTI, Archetypes, Astrology, Chakras)',
      '2 free sessions in The Collective',
      'Eligibility to apply for The Collective',
    ],
  },
  planner: {
    id: 'planner',
    name: 'The Mindful Muse Quarterly Planner',
    slug: 'mindful-muse-quarterly-planner',
    price: 15,
    description: 'Quarterly planner designed for musicians lives & schedules',
    image: '/BootsOnPedals.png',
    includes: [
      'The Mindful Muse Quarterly Planner',
      'Quarterly planning system',
      'Habit tracking',
      'Creative prompts',
      'Reusable digital format',
    ],
  },
  bogo: {
    id: 'bogo',
    name: 'BOGO - Buy One, Gift One Guide',
    slug: 'bogo-buy-one-gift-one',
    price: 100,
    description: 'Get the Guide for yourself and gift one to another artist',
    image: '/BOGOGIRLS.png',
    includes: [
      '2x The Mindful Musicpreneur Guide',
      '2x Mindful Muse Quarterly Planner',
      '2x Eligibility to apply for The Collective',
      '4x free Collective sessions total',
      'Rise together with a friend',
    ],
  },
  freebie: {
    id: 'freebie',
    name: 'Free Resource',
    slug: 'freebie',
    price: 0,
    description: 'Get started with our free resource for female musicians',
    image: '/AppArt.png',
  },
  collective: {
    id: 'collective',
    name: 'The Collective',
    slug: 'the-collective',
    monthlyPrice: 47,
    yearlyPrice: 497,
    description: 'The Personal Power Happy Hour™ For Female Musicians',
    image: '/TheCollectiveBlack.png',
    includes: [
      'Live Monthly Collective Sessions',
      'Journal Jams & Guided Work Sessions',
      'Therapist-led Mental Health Support',
      'Music Industry Pros & Special Guests',
      'Access to Sonic Journey Playlists',
      'Open Q&A / Hot Seats',
      'Private Community Space',
      'Resource Library & Replays',
      'Complimentary Private Substack Membership',
    ],
  },
} as const

export type ProductType = keyof typeof PRODUCTS
